### ISSUE TITLE
 Error looking up user: "www". user: Lookup requires cgo

### ISSUE THREAD

**Issue by nbari** [immortal/immortal#10]
When downloading the precompiled binaries, this error may appear:

     Error looking up user: "www". user: Lookup requires cgo

Seems that is not currently possible to cross compile using `cgo`, therefore need to way to create the binaries on the native platforms.

Compiling from sources solves this problem.

https://golang.org/cmd/cgo/

**Comment by nbari** [comment]
For now, putting here binaries compiled for the proper architecture:

https://github.com/immortal/immortal/releases

Since is going to be complex to cover all architectures, better improve the docs, Makefile to allow build the binaries on the desired target.

For NetBSD/OpenBSD try to port the FreeBSD port

**Comment by elcritch** [comment]
Same problem on linux/arm. Needs to have `cgo` installed. 

This project might provide a solution for better cross compiling: https://github.com/karalabe/xgo

**Comment by nbari** [comment]
@elcritch, please give a try to this binaries https://github.com/immortal/immortal/releases, they were compiled in Linux and should be working.

Or compile from source: http://immortal.run/source/, I tried the FreeBSD-arm version and working fine, but need to specify the arch like this:

    env GOOS=freebsd GOARCH=arm GOARM=6 go make

**Comment by elcritch** [comment]
I tried the releases binary for arm (raspberry pi), but it gave the error:

```
 Error looking up user: "couchdb". user: Lookup requires cgo
```

**Comment by elcritch** [comment]
However, I compiled immortal using `xgo` with these commands:

```shell
xgo --tags 0.11.0 --targets=linux/* -ldflags "-X main.version=0.10.5" -out immortal --buildmode=exe --pkg cmd/immortal github.com/immortal/immortal
xgo --tags 0.11.0 --targets=linux/* -ldflags "-X main.version=0.10.5" -out immortaldir --buildmode=exe --pkg cmd/immortaldir github.com/immortal/immortal
xgo --tags 0.11.0 --targets=linux/* -ldflags "-X main.version=0.10.5" -out immortalctl --buildmode=exe --pkg cmd/immortalctl github.com/immortal/immortal
```

This produced cross-compiled binaries which work fine!

**Comment by nbari** [comment]
Nice, I will give a try and put available the files on the release.

Are you using version `0.11.0` or `0.10.5`, or was a typo from the args you used for `xgo`?

**Comment by elcritch** [comment]
Great! I look forward to trying it out. 

No, the 0.10.5 was copied from the running `make` in the 0.11.0 branch. I suspect it's a typo, but I left it in case. I tried compiling one w/o the `-ldflags "-X main.version=0.10.5"` at all and it seemed to work.
