### ISSUE TITLE
Is it possible to make immortal load environment variables from the actual environment?

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [immortal/immortal#24]
It seems if i don't supply the ```env:``` dictionary in the yaml file, then the environment variables from the OS are not available to the process. Is it possible to have them pass through?

**Comment by nbari** [comment]
Hi @alexzaytsev-newsroomly it should do it, but probably will not load the environment set for your current user, each process gets its own default environments defined by your setup. if your OS is Linux you can edit the `/etc/environment` and make it global for all.

There are two ways to load more environments, one is using the `env:` in the yaml file, another  one is to write them within a directory and use the option `-e /path/to/dir` in where the format should be something like:

    $ ls /path/to/dir
    FOO BAR 

contents of `FOO` will be a string (your variable) same has `BAR`, for more info check the almost at the beginning of man page: https://immortal.run/post/immortal/

you could give a try to run this small script within immortal to print your variables or to log them to a file:


```python
#!/usr/bin/env python                     

import os                                 
import time                               
from os.path import expanduser            

home = expanduser("~")                    

print "getuid: ",  os.getuid()            
print "getgid: ",  os.getgid()            
print "getlogin: ",  os.getlogin()        
print "home: ", home                      

print "\n"                                

for a in os.environ:                      
    print "%s: %s" % (a,  os.getenv(a))   

time.sleep(30)                            

print "\n"       
```

And use this env.yml

```yaml
cmd: su -m your-user -c "/home/LAB/env.py"
cwd: /tmp
env:
  FOO: foo
  BAR: bar
log:
    file: /var/log/env.log
```

The `-m` will leave the environment unmodified.

**Comment by nbari** [comment]
hi @alexzaytsev-newsroomly did you manage to make it work?

**Comment by nbari** [comment]
ok, will close the issue, for now, please feel free to create more if required
