### ISSUE TITLE
improve tests for scandir.go

### ISSUE THREAD

**Issue by nbari** [immortal/immortal#25]
improve tests for [scandir.go](https://github.com/immortal/immortal/blob/master/scandir.go)  and [watchdir.go](https://github.com/immortal/immortal/blob/master/watchpid.go) mainly the onew using **kqueue** (freebsd netbsd openbsd dragonfly darwin)

    func (s *ScanDir) Start(ctl Control) {}

and 

    func (s *ScanDir) Scandir(ctl Control) error {}

**Comment by yogesh-desai** [comment]
Hi @nbari 
Could you please explain more about it? Specifically, what you mean by,
> mainly the onew using kqueue (freebsd netbsd openbsd dragonfly darwin)

**Comment by nbari** [comment]
It probably helps to mention that `kqueue` is not available in Linux therefore for BSD systems the tests need to be improved. 

For example if you are in mac, after cloning the repo type  `make cover` (you may need `make get` before).  That will open a browser and show the overall coverage in where you will notice that `scandir.go` and  `watchdir.go`  need some improvements/refactoring in order to improve the tests/coverage.
