### ISSUE TITLE
Tests not passing using travis Go:tip under mac os

### ISSUE THREAD

**Issue by nbari** [immortal/immortal#27]
Find out why tests are not passing on Travis (develop branch) only when OS is mac os and go version is `tip` https://travis-ci.org/immortal/immortal/jobs/283863933

**Comment by adamo57** [comment]
I could look at this

**Comment by adamo57** [comment]
I found in the build logs that the error is `a_test.go:13: Expected:  (type string)  Got: no such process (type string)  in /Users/travis/gopath/src/github.com/immortal/immortal/signals_test.go:182`

**Comment by nbari** [comment]
Something probably within Travis, working now
