### ISSUE TITLE
improve documentation 

### ISSUE THREAD

**Issue by nbari** [immortal/immortal#36]
Improve the overall documentation, for the example in the [run.yml](https://immortal.run/post/run.yml/) there is no explanation about how to avoid rotating logs, something that could be done by just omitting the options `age`, `num`, `size` etc.

Be more clear, add more examples (avoid assumptions)

**Comment by yogesh-desai** [comment]
Hi @nbari 
So, do you mean to add extra information in the readme, when we just skip the flags; `age`, `num` and `size`?
```
log:
    file: /var/log/app-1.log
```
The above config will avoid the `log-rotate`, right? If yes, then I have raised PR https://github.com/immortal/immortal/pull/52
Please kindly review and give your feedback.

Thank you.

**Comment by nbari** [comment]
hi @yogesh-desai that helps, thanks.

**Comment by nbari** [comment]
hi @yogesh-desai do you think could add your changes to the web docs (https://immortal.run/post/immortal/ in https://github.com/immortal/docs/edit/master/post/immortal.md), thanks in advance

**Comment by yogesh-desai** [comment]
Hi @nbari 
Could you please create an issue with `Hacktoberfest` label in the repo? I would be happy to contribute.

**Comment by nbari** [comment]
Hi @yogesh-desai https://github.com/immortal/immortal/issues/53 hope is ok

**Comment by yogesh-desai** [comment]
Can we close this issue as well @nbari? Let me know your thoughts if you think to add more.
