### ISSUE TITLE
Releases do not contain man pages?

### ISSUE THREAD

**Issue by jsumners** [immortal/immortal#37]
It seems the pre-built binary releases do not contain the man pages. Is there a reason for this?

**Comment by nbari** [comment]
Hi @jsumners thanks for catching this out,  I need to find a way of how to include them, for now, I am using [goxc](https://github.com/laher/goxc)  will look more into this, any ideas are more than welcome.

**Comment by jsumners** [comment]
I really don't know anything about the Go ecosystem. I just found this project yesterday and liked its simplification of deploying a runit style supervisor for user level services. I am thinking about integrating into future system builds by simply acquiring the release and unpackaging it to the right locations via an Ansible playbook.

**Comment by nbari** [comment]
Hi @jsumners nice to ear that just in case I added the ansible role that I have been using here: https://github.com/immortal/ansible and some info about how I use it here https://immortal.run/post/ansible/, hope it can help.

**Comment by nbari** [comment]
Fixed in 0.19.0 using now https://packagecloud.io/immortal/immortal, still work in progress to support mulitple architectures
