### ISSUE TITLE
immortaldir not starting services

### ISSUE THREAD

**Issue by serussell** [immortal/immortal#38]
`immortaldir` does not start services when running immortal _entirely_ from a user `$HOME` -- with *no* access to root directories.

## Setup

```
$HOME/local/bin/immortal
$HOME/local/bin/immortaldir
$HOME/local/bin/immortalctl
$HOME/local/var/run/immortal
$HOME/local/etc/immortal/app.yml
```

## Success with `immortal`

```
cd $HOME/local
./bin/immortal -c etc/immortal/app.yml
```

This works; `bin/immortalctl status` shows the service started & `app` is running.  I can stop, restart, and otherwise control `app` through `immortalctl` as expected. However...

## Failure with `immortaldir`

```
cd $HOME/local
IMMORTAL_SDIR=$HOME/local/var/run/immortal ./bin/immortaldir etc/immortal
```

results in

```
2018/04/17 22:28:36 immortal scandir: /home/uzr/local/etc/immortal
2018/04/17 22:28:36 Starting: app
2018/04/17 22:28:36
2018/04/17 22:28:41 Starting: app
2018/04/17 22:28:41
```

and so on, repeatedly.  No errors, no logging, no way to figure out what's going wrong.  `app` is not started nor is running.

## Expected behavior

An app that can be successfully started with `immortal` should work when started with `immortaldir`.

**Comment by nbari** [comment]
hi @serussell can you try to add to your path the location of `immortal`, give a try to:

    PATH:$HOME/local/bin/immortal:$PATH

`immortalctl` relies on the PATH to find `immortal`

**Comment by serussell** [comment]
Hi @nbari -- I think I did read that somewhere.  I did so; it doesn't make a difference:

```
app% immortaldir etc/immortal                                                  
2018/04/18 20:25:52 immortal scandir: /home/uzr/local/etc/immortal
2018/04/18 20:25:52 Starting: caddy
2018/04/18 20:25:52 
2018/04/18 20:25:52 Starting: node_exporter
2018/04/18 20:25:52 
2018/04/18 20:25:52 Starting: oklog
2018/04/18 20:25:52 
2018/04/18 20:25:57 Starting: caddy
2018/04/18 20:25:57 
2018/04/18 20:25:57 Starting: node_exporter
2018/04/18 20:25:57 
2018/04/18 20:25:57 Starting: oklog
... (many of these)
^C
app% immortal -c etc/immortal/oklog.yml 
app% immortal -c etc/immortal/caddy.yml 
app% immortal -c etc/immortal/node_exporter.yml 
app% immortalctl
 PID      Up   Down   Name   CMD
8598   16.8s          8541   /home/uzr/local/bin/oklog ingeststore -store.segment-replication-factor 1
8630    5.6s          8617   ./caddy
8656    1.7s          8645   ./bin/node_exporter
```
Before I did `^c` on `immortaldir`, I checked in another term to make sure that none of the services were running.

**Comment by nbari** [comment]
@serussell can you please show an example of `oklog.yml` seems to be looping, try to check the logs by using something like:

    cmd: your-comand
    log:
      file: /var/log/oklog.log

Probaly is related to not having rights to write to `/var/run/immortal` you can change that directory setting the environment var `IMMORTAL_SDIR` for example:

    export IMMORTAL_SDIR=$HOME/test/immortal/

**Comment by serussell** [comment]
Very interesting.  I'd set it before but hadn't after adding the path.

So, the summary fix was: have the `immortal*` programs in PATH and set `IMMORTAL_SDIR` to a user-write-able directory.  It's working now -- thank you!

**Comment by nbari** [comment]
@serussell nice that you manage it to make it work, if found any other issue please don't hesitate on creating an issue. 👍
