### ISSUE TITLE
How do you stop a process?

### ISSUE THREAD

**Issue by superjose** [immortal/immortal#44]
Hi :). Sorry for opening up a GitHub issue. I just can't predictably stop an immortal service with `immortalctl`. 

The service doesn't appear without sudo. 

So I always try the following 
immortalctl stop <process-name>
immortalctl stop <process-id>
sudo immortalctl stop <process-name>
sudo immortalctl stop <process-id>
sudo immortalctl -k <process-id>
sudo immortalctl -k <process-name>
immortalctl -k <process-id>
immortalctl -k <process-name>
set IMMORTAL_EXIT=exit sudo immortalctl exit run
sudo IMMORTAL_EXIT=exit immortalctl exit run (Where run is the process name - see pictures).
sudo immortalctl halt "*" And it comes back to life in about 5 seconds.
sdo immortalctl exit <process-id>
sudo IMMORTAL_EXIT=exit immortalctl exit "*"

And nada.

<img src="https://i.stack.imgur.com/fwTFb.png" alt="Immortalctl command line"/>

https://askubuntu.com/a/1088357/806019

The question is... how do I stop a service?

**Comment by nbari** [comment]
Hi @superjose nice thing is that your process seems to be well immortalized and not dying easy :-) 

I answerd here https://askubuntu.com/a/1090481/710912 

Give a try, if need extra help or find an issue please [don't heasitate on creating another issue](https://github.com/immortal/immortal/blob/master/CONTRIBUTING.md)

**Comment by superjose** [comment]
Hahahah, yeah :D Awesome!!  I'll let you know!!

**Comment by nbari** [comment]
@superjose Also keep in mind that the output of `immortalctl` depends on the user running the command if you started a process within your user (not root) you will see only lor "local" processes `$HOME/.immortal` not the ones started from the `$ROOT` on `/var/run/immortal`

**Comment by seliestel** [comment]
I have a similar problem:

I installed immortal.run and immortalized a process on WSL2 Ubuntu to try it. But I didn't set up immortalctl or immortaldir. Now, I cannot find the way to kill this process. When I run "immortalctrl" or "sudo immortalctrl" there are no processes listed. But I can see that they are running from htop. I have also not found any run.yml file anywhere or even an /.immortal directory anywhere in the file system. 

Maybe the developers went too far in their search for immortality? 

I would really appreciate any recommendations on how to kill this process.
