### ISSUE TITLE
validate config file

### ISSUE THREAD

**Issue by shomodj** [immortal/immortal#47]
is there a way to validate config file?

**Comment by nbari** [comment]
Hi @shomodj is tested/parsed when using it so if there is an error it should tell you, for example if you use this [`bad-run.yml`](https://github.com/immortal/immortal/blob/master/example/bad-run.yml), you will get an error like this:

    $ immortal -c bad-run.yml
    missing command, use ("immortal -h") for help

Are you having some issues with a specific configuration file?

**Comment by shomodj** [comment]
No I don't have issues, I just want to validate the file before issuing restart command, this is a normal behaviour in ansible so it will tell me that the file is wrongly formatted and not try and restart the service

**Comment by shomodj** [comment]
most OSS has this option
https://www.configapp.com/2018/01/09/configuration-file-validation-check/

**Comment by nbari** [comment]
Hi @shomodj I think is somethig that could be implemented, I am thinking on printing the full config file if everything is ok and if not an error that could help to identify the issue besides exiting with > 0

**Comment by nbari** [comment]
Hi @shomodj if possible please try/test the develop branch, the option `-cc` has been implemented, it will print the config file and `exit 0` if no errors found, it will `exit 1` otherwise

**Comment by nbari** [comment]
@shomodj please try version `0.23.0`
