### ISSUE TITLE
Immortal on Raspberry

### ISSUE THREAD

**Issue by magellan-13016** [immortal/immortal#48]
Hi !
I'm using immortal with Linux Mint and the SSTV software since this program is buggy and exit itself whenever while it must receive SSTV pictures from ISS. So in order to avoid missing pictures from the International Space Station, Immortal is a must have software. 
I've just installed QSSTV on my raspberry and I didn't find any package for Raspbian and ARM device working for my Raspbian under Raspberry. I've passed many hours to try to compile the software but I never succeed.

So can someone help me to get a working package or un very good tutorial about how to compile this software for my raspberry ? New pictures are being sent this week-end from ISS...

Many thanks to all people who will help me.

David.

**Comment by nbari** [comment]
hi @magellan-13016 there are some arm packages available here: https://packagecloud.io/app/immortal/immortal/search?q=arm

for  linux `deb` based distros you could just do:

    curl -s https://packagecloud.io/install/repositories/immortal/immortal/script.deb.sh | sudo bash

For linux more info can be found here  https://packagecloud.io/immortal/immortal/install.

**Comment by magellan-13016** [comment]
Thanks for your answer but I already tried this :

**_pi@raspberrypi:~ $ curl -s https://packagecloud.io/install/repositories/immortal/immortal/script.deb.sh | sudo bash
Detected operating system as raspbian/stretch.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/immortal_immortal.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done._**

The repository is setup! You can now install packages.

And after I tried this :

_**pi@raspberrypi:~ $ sudo apt-get install immortal
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet immortal**_

In English, impossible to find the package immortal.

**Comment by nbari** [comment]
hi @magellan-13016 please give a try to one of this: https://dl.bintray.com/nbari/immortal/ 

probably https://dl.bintray.com/nbari/immortal/:immortal_0.22.0_linux_arm.tar.gz

You would just need to copy the 3 binaries to `/usr/local/bin`

**Comment by magellan-13016** [comment]
Oh yeah !
It works like a charm !
Many many thanks for your help !
David.

**Comment by magellan-13016** [comment]
I'm now searching a way to end my program without using the terminal. 
I have made this script but I always have to type the number of the process I want to terminate.
Do you have a solution for me to avoid having to type the number of the process I want to close ?
Here is the script :

**_#!/bin/bash

echo
echo =================
echo = List of active programs =
echo =================
echo

immortalctl

echo
echo "Enter the number of the program to terminate (column 'Name', green number):"

read pid

immortalctl stop $pid
immortal exit $pid

echo
echo ===================
echo = New list of active programs =
echo ===================
echo

immortalctl

echo
read -p "Press Enter to end..."_**

**Comment by nbari** [comment]
Use [immortaldir](https://immortal.run/post/immortaldir/) check how to use it and boot time here https://immortal.run/post/how-to-install/

That way if you you use for example `/etc/immortal` by just removing your `test.yml` files from there
it will stop them.

Or use option `-c` for example:

    immortal -c test.yml 

Check more about it here https://github.com/immortal/immortal/pull/39

**Comment by magellan-13016** [comment]
I don't need my app (QSSTV) to run at boot time. I just want a way to end my app "qsstv" quicly with a shortcut on the desktop since when I start it with immortal, the only way I found to end the program is by using the terminal and my script.

**Comment by nbari** [comment]
A more complex setup that could work by just visiting a link, could be to expose the socket with Nginx, check this post: https://immortal.run/post/nginx/, therefore, you could just have a shortcut calling a URL to something that coluld call `http://localhost/signal/stop`

**Comment by magellan-13016** [comment]
Many thanks. I will try to understand all things but it seems to be a little complicated to understand for me. I think the best way is that someone help me to get the green number pid  that immortalctl is diplaying so I just send the command immortalctl stop $pid and immortal exit $pid with the green number I extract from the displayed process handle by immortal.

**Comment by nbari** [comment]
Hi @magellan-13016, if you want to use a name instead of a pid here is a very basic exampe:

Create a file `test.yml` with this content:

    cmd: sleep 3

Now just run `immortal -c test.yml`

if you then run `immortalctl` and you will see somthing like:

```
$ immortalctl
  PID     Up   Down   Name   CMD
13879   0.2s          test   sleep 3
```

You could create another file `my-script.yml`:

     cmd: my-script.sh

and run `immortal -c my-script.yml`

And you will see `my-script` instead of the pid.

Give a try if find any issue don't heasitate on creating another issue.

**Comment by magellan-13016** [comment]
Ok my friend, this is a big step to the goal ! Thanks to your help, I can now exit my app with the name given to the yml file with the command immortalctl stop "name" but after it is impossible to restart it until I run immortalctl start "name". 

Is it a way to use immortal -c file.yml with the command start ?

**Comment by nbari** [comment]
hi @magellan-13016 that's how it is designed to be, you just need to start it once and forget about it, since it will try to run it forever.

**Comment by nbari** [comment]
I am closing this for now, feel free to open it if required.
