### ISSUE TITLE
as Docker container process manager

### ISSUE THREAD

**Issue by mhf-ir** [immortal/immortal#49]
1. Documentation needed for using immortal as non-dependency binary file as container entry point multi services container.
See supervisord as python process manager.
https://docs.docker.com/config/containers/multi-service_container/

2. And how to healtheck for container will work?
https://docs.docker.com/engine/reference/builder/#healthcheck

3. and some example to open nginx or pm2 or phpfpm or another application for immortal subprocess and immortal lead them all and report docker engine that container is healthy or not.

It's will be awesome.

**Comment by nbari** [comment]
hi @mhf-ir all this is already supported check the docs here including some examples: https://immortal.run/post/examples/ if there is something not clear or that needs to be added please feel free to create an issue
