### ISSUE TITLE
Log files reopening

### ISSUE THREAD

**Issue by nordicdyno** [immortal/immortal#50]
Is there any way to reopen log files managed by immortal?
What do you think about implementing a such feature (by catching SIGUSR2 like supervisord do) to avoid dependency on any external log manager?

**Comment by nbari** [comment]
Hi @nordicdyno could you please elaborate more, maybe an example of what you want to do could help.

**Comment by olgeni** [comment]
Hi,

If some log rotation utility renames the immortal log file while it is still open, the process will keep writing on the old file and the new file will be left untouched 😅

If you close and then reopen the log file based on some external signal (USR2, HUP, etc.) then you can prevent it.

**Comment by olgeni** [comment]
Now I see that log rotation is already supported so I'm not really sure about the use case 👀
