### ISSUE TITLE
Custom 'cleanup' action

### ISSUE THREAD

**Issue by olgeni** [immortal/immortal#54]
Hi,

Would it be possible to integrate some kind of custom cleanup action after the process from “cmd” finishes? Something to be executed with the exit code as a parameter, that could perform some extra actions before the main process is restarted (or just after it is shut down.)

I have a 'cmd' script that uses “exec” to start the main service so that it can be managed properly, but when it stops I'm left with a few ifconfig commands to run to ensure the proper teardown sequence 😅

**Comment by nbari** [comment]
probably you could use the `require_cmd` option

> The require_cmd option will execute a command and if the exit status is 0 it will start the service, example:
    
    require_cmd:  test -f /tmp/foo

**Comment by nbari** [comment]
I think could be a useful option,  what about having something like `post_exit` so that like you mention, exactly after the process exists if will call the script/command (could be something like metrics) and not bound to the defined `wait` if any, for example, something like: 

```
cmd: your-app
require_cmd: test -f /tmp/foo
post_exit: telegraf.sh
wait: 3
```

**Comment by nbari** [comment]
@olgeni give a try to latest develop version, tests still pending but should do the work (https://github.com/immortal/immortal/commit/cf58467fef6d9347c9629bbf3292732d37aec796)

**Comment by olgeni** [comment]
It works 🙌 Thank you!

Is there a way to pass the exit code from the main process?

**Comment by nbari** [comment]
Should be possible, in this you mean as the first argument to the script called if `post_exit` is defined right?

**Comment by olgeni** [comment]
Yup - so you could send alerts, or leave some state for required_cmd to check on the next run..

**Comment by nbari** [comment]
hi  @olgeni please give a try to https://github.com/immortal/immortal/commit/14257532a583255d8df3af5b6ca6c29785a4bab8, still test missing but I think it may work.

**Comment by olgeni** [comment]
I don't see it with dtrace - the exit code gets lost somewhere in the shell 😅

It works if I change it like this:

`exec.Command(shell, "-c", fmt.Sprintf("%s %d", s.daemon.cfg.PostExit, exitcode)).Run()`

**Comment by nbari** [comment]
@olgeni I just update it, please give a try, can you share you are you testing with `dtrace` thanks in advance.

**Comment by olgeni** [comment]
Now I can see it 🙌

Quick check:

```
cmd: sleep 10
post_exit: logger "exit code:"
```

dwatch -X proc

```
2019 Oct 20 20:14:19 0.0 sleep[39103]: SEND SIGCHLD[20] pid 39102 -- immortal -c /usr/local/etc/immortal/test.yml -ctl test
2019 Oct 20 20:14:19 0.0 immortal[39102]: FORK pid 39105 -- immortal -c /usr/local/etc/immortal/test.yml -ctl test
2019 Oct 20 20:14:19 0.0 immortal[39105]: EXEC /bin/sh
2019 Oct 20 20:14:19 0.0 sh[39105]: INIT sh -c logger "exit code:" 0
2019 Oct 20 20:14:19 0.0 sh[39105]: EXEC /usr/bin/logger
2019 Oct 20 20:14:19 0.0 logger[39105]: INIT logger exit code: 0
2019 Oct 20 20:14:19 0.0 logger[39105]: EXIT child exited
2019 Oct 20 20:14:19 0.0 logger[39105]: SEND SIGCHLD[20] pid 39102 -- immortal -c /usr/local/etc/immortal/test.yml -ctl test
2019 Oct 20 20:14:19 0.0 immortal[39102]: FORK pid 39106 -- immortal -c /usr/local/etc/immortal/test.yml -ctl test
2019 Oct 20 20:14:19 0.0 immortal[39106]: EXEC /bin/sleep
2019 Oct 20 20:14:19 0.0 sleep[39106]: INIT sleep 10
```

**Comment by nbari** [comment]
implemented in https://github.com/immortal/immortal/releases/tag/0.24.0

**Comment by olgeni** [comment]
🙌 Thanks! 🙌
