### ISSUE TITLE
immortaldir crashes with a high number of processes

### ISSUE THREAD

**Issue by mradspieler** [immortal/immortal#56]
### What did you do?
I would like to start/manage about 1500 processes via immortal. But unfortunately after about 100-200 processes immortaldir crashes. As soon as I create more than 200 yml files in the immortaldir directory, immortaldir crashes.

yml file content is always the same:
`cmd: sleep 3600`

### What did you expect to see?
It should be possible to manage 1500 processes

### What did you see instead?
immortal crashed.
Jan 07 21:54:49  immortaldir[3501265]: 2020/01/07 21:54:49 runtime: failed to create new OS thread (have 6 already; errno=11)
Jan 07 21:54:49  immortaldir[3501265]: runtime: may need to increase max user processes (ulimit -u)
Jan 07 21:54:49  immortaldir[3501265]: fatal error: newosproc
Jan 07 21:54:49  immortaldir[3501265]: runtime stack:
Jan 07 21:54:49  immortaldir[3501265]: runtime.throw(0x7b2dc0, 0x9)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/panic.go:774 +0x72
Jan 07 21:54:49  immortaldir[3501265]: runtime.newosproc(0xc000080000)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/os_linux.go:153 +0x1ba
Jan 07 21:54:49  immortaldir[3501265]: runtime.newm1(0xc000080000)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:1853 +0xdc
Jan 07 21:54:49  immortaldir[3501265]: runtime.newm(0x7cce20, 0xc000029400)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:1832 +0x8f
Jan 07 21:54:49  immortaldir[3501265]: runtime.startm(0x0, 0xc000026f01)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:1969 +0x12a
Jan 07 21:54:49  immortaldir[3501265]: runtime.wakep(...)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:2050
Jan 07 21:54:49  immortaldir[3501265]: runtime.resetspinning()
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:2430 +0x93
Jan 07 21:54:49  immortaldir[3501265]: runtime.schedule()
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:2531 +0x2a0
Jan 07 21:54:49  immortaldir[3501265]: runtime.park_m(0xc000000600)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:2610 +0x9d
Jan 07 21:54:49  immortaldir[3501265]: runtime.mcall(0x0)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
Jan 07 21:54:49  immortaldir[3501265]: goroutine 1 [chan receive, locked to thread]:
Jan 07 21:54:49  immortaldir[3501265]: runtime.gopark(0x7cce70, 0xc000060058, 0x170e, 0x3)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:304 +0xe0
Jan 07 21:54:49  immortaldir[3501265]: runtime.goparkunlock(...)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:310
Jan 07 21:54:49  immortaldir[3501265]: runtime.chanrecv(0xc000060000, 0x0, 0xc000000101, 0x410101)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/chan.go:524 +0x2e8
Jan 07 21:54:49  immortaldir[3501265]: runtime.chanrecv1(0xc000060000, 0x0)
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/chan.go:406 +0x2b
Jan 07 21:54:49  immortaldir[3501265]: runtime.gcenable()
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/mgc.go:213 +0xac
Jan 07 21:54:49  immortaldir[3501265]: runtime.main()
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/proc.go:166 +0x121
Jan 07 21:54:49  immortaldir[3501265]: runtime.goexit()
Jan 07 21:54:49  immortaldir[3501265]:         /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1

### Is it possible to reproduce?
Yes on Ubuntu and SLES distributions

### Hardware
8 Cores
8 GB RAM

**uname -a**
Linux 4.12.14-95.29-default #1 SMP Thu Aug 1 15:34:33 UTC 2019 (47e48a4) x86_64 x86_64 x86_64 GNU/Linux

**ulimit -a**
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31295
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1042101
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2097151
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by nbari** [comment]
Hi @mradspieler how are you running, calling **immortal**?  in the same way (shell/user) can you try something like this:
    
    for i in {1..200}; do sleep 3600 &; done

If using `immortaldir` try https://immortal.run/post/how-to-install/

**Comment by mradspieler** [comment]
Hi @nbari,

thanks for your reply.
we are using immortaldir, and installed it as described in https://immortal.run/post/how-to-install/

But now we are able to deal with the crash with the following workaround:

new settings in /etc/security/limits.conf

_root     soft    nproc            unlimited
root     hard    nproc            unlimited
\*        soft    nproc            2097151
\*        hard    nproc            4194303_

increase pid_max from 32768 to 4194303
_sudo sysctl -w kernel.pid_max=4194303_

increase open files from 4096 to 1042101
_ulimit -n 1042101_

number of running processes on that machine:
$ ps -eLf | wc -l
740

if we use the default settings from our distributions (ubuntu, sles), immortaldir still crashes.

Any idea why immortaldir needs so many open files and high pid_max setting?

**Comment by nbari** [comment]
Hi @mradspieler is not that `immortal` needs to many open files, that is more related to the imposed limits by your OS and the amount of process you are creating
