### ISSUE TITLE
immortal 0.24.0/0.24.1 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [immortal/immortal#57]
Relates to 
- https://github.com/Homebrew/homebrew-core/pull/45928
- https://github.com/Homebrew/homebrew-core/pull/47622

It looks like we cannot build immortal from the source code (I just tried on my local machine, I wonder if you can provide some instructions to keep the formula up to date). Thanks!

cc @nbari

**Comment by nbari** [comment]
Hi @chenrui333 many thanks for trying, could you please give a try to latest release https://github.com/immortal/immortal/releases/tag/0.24.2, I updated the dependencies, probably that could help, fix the issue.

How could I test also the formula before trying to bump?

**Comment by chenrui333** [comment]
my understanding is your file structure got changed since last workable release.

**Comment by chenrui333** [comment]
My another goal is to move this repo to use go modules (https://github.com/Homebrew/homebrew-core/issues/47627), and I created a new PR on this theme.

**Comment by nbari** [comment]
Hi @chenrui333, thanks for the PR 👍 build still working but how to deal now with the homebrew formula?

**Comment by nbari** [comment]
https://github.com/Homebrew/homebrew-core/pull/52015
