### ISSUE TITLE
Are packagecloud immortal packages still maintained?

### ISSUE THREAD

**Issue by halmartin** [immortal/immortal#60]
Hello, sorry if a GitHub issue is not the correct place to raise this.

I was following the [installation instructions](https://immortal.run/post/how-to-install/) for immortal and noticed two issues:

1. The latest version available on [packagecloud](https://packagecloud.io/immortal/immortal) is 0.23.1 while it seems from the [GitHub releases](https://github.com/immortal/immortal/releases), that the latest stable release is 0.24.3
1. There are no packages for Ubuntu 20.04 (focal). The installation script on packagecloud attempts to generate an [immortal_immortal.list](https://packagecloud.io/install/repositories/immortal/immortal/config_file.list?os=Ubuntu&dist=focal&source=script) for focal, and this fails as no package for this release has been created on packagecloud.

It is not possible to install immortal on Ubuntu Focal:
```
Ign:6 https://packagecloud.io/immortal/immortal/ubuntu focal InRelease
Err:7 https://packagecloud.io/immortal/immortal/ubuntu focal Release
  404  Not Found [IP: 2600:1f1c:2e5:6900:5df8:6a7b:6fb7:c697 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/immortal/immortal/ubuntu focal Release' does not have a Release file.
```

I did a bit of searching, but I cannot find any other source of immortal deb packages.

Thank you

**Comment by nbari** [comment]
Hi @halmartin thanks for the heads up, can you please try again, the package should be now available for [focal](https://packagecloud.io/immortal/immortal/packages/ubuntu/focal/immortal_0.24.3-2-gaed5591_amd64.deb).

The packages are created using this Dockerfile: https://github.com/immortal/immortal/blob/master/Dockerfile, and just in case this for FreeBSD: https://github.com/freebsd/freebsd-ports/tree/master/sysutils/immortal

**Comment by halmartin** [comment]
Looks good, thanks a lot!

```
$ apt-get update
...
Get:10 https://packagecloud.io/immortal/immortal/ubuntu focal InRelease [23.3 kB]
Get:13 https://packagecloud.io/immortal/immortal/ubuntu focal/main i386 Packages [489 B]
Get:14 https://packagecloud.io/immortal/immortal/ubuntu focal/main amd64 Packages [487 B]
```

```
$ apt-cache policy immortal
immortal:
  Installed: 0.23.0
  Candidate: 0.24.3-2-gaed5591
  Version table:
     0.24.3-2-gaed5591 500
        500 https://packagecloud.io/immortal/immortal/ubuntu focal/main amd64 Packages
```
