### ISSUE TITLE
Stopping a process

### ISSUE THREAD

**Issue by seliestel** [immortal/immortal#63]
I have a similar problem to a previous question: https://github.com/immortal/immortal/issues/44#issuecomment-436243276

I installed immortal.run and immortalized a process on WSL2 Ubuntu to try it. But I didn't set up immortalctrl or immortaldir. Now, I cannot find the way to kill this process. When I run "immortalctrl" or "sudo immortalctrl" there are no processes listed. But I can see that they are running from htop. I have also not found any run.yml file anywhere or even an /.immortal directory anywhere in the file system.

Maybe the developers went too far in their search for immortality?

I would really appreciate any recommendations on how to kill this process. I guess it would not be helpful to uninstall and purge immortal since at this stage the process has been daemonized?

**Comment by nbari** [comment]
hi @seliestel normally you just type `immortalctl` and it will list/show the running process, to stop everything you do something like:

    immortalctl halt *

You are running it like root or as a normal user?

**Comment by seliestel** [comment]
@nbari Thanks for your reply. I was running it as normal user. The immortalctl instructions were not working. I actually solved it by rebooting. After the reboot, the process was not resuscitated. I guess that it had not created the file run.yml in the first place, that's why I couldn't find it.
