### ISSUE TITLE
Custom immortaldir with wildcard?

### ISSUE THREAD

**Issue by pwFoo** [immortal/immortal#64]
I'm searching for a process manager / monitor with wildcard service dir like
```
/services/<service_name>/<service>.yml
```

Would that possible with immortal?

**Comment by nbari** [comment]
Everything within a dir could be started: https://immortal.run/post/immortaldir/ and you could stop all of them using a wildcard:
    
    immortalctl halt "*"

https://immortal.run/post/immortalctl/

hope this helps
